import React, { createContext, useContext, useEffect, useState, useMemo } from "react";
import { doc, onSnapshot, setDoc, collection, addDoc, updateDoc, deleteDoc, query, orderBy, limit } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { restaurant, boltFood, uberEats, maps, lisbonClock, type Localized, type HoursStatus } from "@/lib/restaurant";

export interface DeliveryLinks { whatsapp:string; bolt:string; uber:string; phoneDisplay:string; phoneTel:string; address:string; googleMaps:string; }
export interface DayHours { open:string; close:string; isClosed:boolean; }
export type WeekHours = { monday:DayHours; tuesday:DayHours; wednesday:DayHours; thursday:DayHours; friday:DayHours; saturday:DayHours; sunday:DayHours; };
export interface TickerMessageItem { id:string; textPt:string; textEn:string; active:boolean; }
export interface SettingsData { isOnlineOrderingPaused:boolean; pausedNoticeEn:string; pausedNoticePt:string; deliveryLinks:DeliveryLinks; openingHours:WeekHours; tickerMessages:TickerMessageItem[]; tickerActive:boolean; updatedAt:string; }
export interface Promotion { id:string; title:string; messageEn:string; messagePt:string; isWebsiteOnly:boolean; locations:Array<"ticker"|"homepage"|"menu"|"product">; targetProductId?:string; startDate?:string; endDate?:string; status:"active"|"paused"|"scheduled"; createdAt:string; updatedAt:string; }
export interface DishOverride { price?:number|null; sizePrices?:Record<string,number|null>; isAvailable?:boolean; isFeatured?:boolean; namePt?:string; nameEn?:string; descriptionPt?:string; descriptionEn?:string; imageUrl?:string; }
export interface HistoryItem { id:string; timestamp:string; action:string; details:string; userEmail:string; }

const DEFAULT_HOURS: WeekHours = { monday:{open:"11:00",close:"00:00",isClosed:false}, tuesday:{open:"11:00",close:"00:00",isClosed:false}, wednesday:{open:"11:00",close:"00:00",isClosed:false}, thursday:{open:"11:00",close:"00:00",isClosed:false}, friday:{open:"15:30",close:"00:00",isClosed:false}, saturday:{open:"11:00",close:"00:00",isClosed:false}, sunday:{open:"11:00",close:"00:00",isClosed:false} };
const DEFAULT_TICKER_MESSAGES: TickerMessageItem[] = [
  {id:"1",textPt:"🥙 DONER KEBAB • DURUM • FALAFEL",textEn:"🥙 DONER KEBAB • DURUM • FALAFEL",active:true},
  {id:"2",textPt:"★ OPÇÕES HALAL",textEn:"★ HALAL OPTIONS",active:true},
  {id:"3",textPt:"🍕 PIZZAS • HAMBÚRGUERES • FRANGO & SNACKS",textEn:"🍕 PIZZA • BURGERS • CHICKEN & SNACKS",active:true},
  {id:"4",textPt:"🍽️ PRATOS DE KEBAB • FALAFEL",textEn:"🍽️ KEBAB PLATES • FALAFEL",active:true},
  {id:"5",textPt:"🍟 BATATAS • EXTRAS • BEBIDAS",textEn:"🍟 FRIES • EXTRAS • DRINKS",active:true},
  {id:"6",textPt:"⚡ TAKEAWAY • BOLT FOOD • UBER EATS",textEn:"⚡ TAKEAWAY • BOLT FOOD • UBER EATS",active:true},
  {id:"7",textPt:"🛵 BOLT FOOD COM 30% DE DESCONTO",textEn:"🛵 30% OFF ON BOLT FOOD",active:true},
];
const DAY_KEYS:Array<keyof WeekHours>=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"];
const toManagedMinutes=(hhmm:string,isCloseTime=false)=>{const [hour,minute]=hhmm.split(":").map(Number);if(isCloseTime&&hour===0&&minute===0)return 24*60;return hour*60+minute;};
export function getManagedHoursStatus(openingHours:WeekHours,date:Date=new Date()):HoursStatus{const {day,minutes}=lisbonClock(date);const today=openingHours[DAY_KEYS[day]];if(!today.isClosed){const openM=toManagedMinutes(today.open);const closeM=toManagedMinutes(today.close,true);const isOpen=minutes>=openM&&minutes<closeM;if(isOpen)return{isOpen:true,todayOpen:today.open,todayClose:today.close,opensLaterToday:false,nextOpenDay:day,nextOpenTime:today.open};if(minutes<openM)return{isOpen:false,todayOpen:today.open,todayClose:today.close,opensLaterToday:true,nextOpenDay:day,nextOpenTime:today.open};}for(let offset=1;offset<=7;offset+=1){const nextDay=(day+offset)%7;const next=openingHours[DAY_KEYS[nextDay]];if(!next.isClosed)return{isOpen:false,todayOpen:today.open,todayClose:today.close,opensLaterToday:false,nextOpenDay:nextDay,nextOpenTime:next.open};}return{isOpen:false,todayOpen:today.open,todayClose:today.close,opensLaterToday:false,nextOpenDay:day,nextOpenTime:today.open};}
export function getManagedLiveStatus(openingHours:WeekHours,date:Date=new Date()){const status=getManagedHoursStatus(openingHours,date);if(status.isOpen)return{...status,label:{pt:`Aberto agora · até às ${status.todayClose}`,en:`Open now · until ${status.todayClose}`} as Localized};if(status.opensLaterToday)return{...status,label:{pt:`Fechado · Abre hoje às ${status.todayOpen}`,en:`Closed · Opens today at ${status.todayOpen}`} as Localized};return{...status,label:{pt:`Fechado · Abre às ${status.nextOpenTime}`,en:`Closed · Opens at ${status.nextOpenTime}`} as Localized};}
export const DEFAULT_SETTINGS:SettingsData={isOnlineOrderingPaused:false,pausedNoticeEn:"Online ordering is temporarily unavailable. Please call us or visit our restaurant directly.",pausedNoticePt:"Pedidos online temporariamente indisponíveis. Por favor ligue-nos ou visite o nosso restaurante diretamente.",deliveryLinks:{whatsapp:restaurant.whatsapp,bolt:boltFood.storeUrl,uber:uberEats.storeUrl,phoneDisplay:restaurant.phoneDisplay,phoneTel:restaurant.phoneTel,address:`${restaurant.address.street}, ${restaurant.address.postalCode} ${restaurant.address.locality}`,googleMaps:maps.search},openingHours:DEFAULT_HOURS,tickerMessages:DEFAULT_TICKER_MESSAGES,tickerActive:true,updatedAt:new Date().toISOString()};

interface RestaurantContextType { settings:SettingsData; promotions:Promotion[]; menuOverrides:Record<string,DishOverride>; history:HistoryItem[]; isLoading:boolean; error:string|null; isPromotionActiveNow:(promo:Promotion)=>boolean; activePromotions:Promotion[]; getDishPrice:(dishId:string,defaultPrice:number|null)=>number|null; getDishSizePrice:(dishId:string,sizeId:string,defaultPrice:number|null)=>number|null; isDishAvailable:(dishId:string)=>boolean; isDishFeatured:(dishId:string,defaultFeatured:boolean)=>boolean; getDishName:(dishId:string,defaultName:Localized)=>Localized; getDishDescription:(dishId:string,defaultDesc?:Localized)=>Localized|undefined; getDishImage:(dishId:string,defaultImage?:string)=>string|undefined; updateSettings:(newSettings:Partial<SettingsData>,userEmail?:string)=>Promise<void>; updateDishOverride:(dishId:string,override:Partial<DishOverride>,userEmail?:string,actionName?:string)=>Promise<void>; toggleDishAvailability:(dishId:string,isAvailable:boolean,dishName?:string,userEmail?:string)=>Promise<void>; savePromotion:(promo:Omit<Promotion,"createdAt"|"updatedAt">|Promotion,userEmail?:string)=>Promise<void>; togglePromotionStatus:(id:string,newStatus:"active"|"paused"|"scheduled",userEmail?:string)=>Promise<void>; deletePromotion:(id:string,userEmail?:string)=>Promise<void>; recordHistory:(action:string,details:string,userEmail?:string)=>Promise<void>; }
const RestaurantContext=createContext<RestaurantContextType|null>(null);
export function RestaurantDataProvider({children}:{children:React.ReactNode}){
  const [settings,setSettings]=useState<SettingsData>(()=>{if(typeof window!=="undefined"){try{const cached=localStorage.getItem("bk_settings");if(cached)return{...DEFAULT_SETTINGS,...JSON.parse(cached)};}catch{}}return DEFAULT_SETTINGS;});
  const [promotions,setPromotions]=useState<Promotion[]>([]);
  const [menuOverrides,setMenuOverrides]=useState<Record<string,DishOverride>>(()=>{if(typeof window!=="undefined"){try{const cached=localStorage.getItem("bk_menu_overrides");if(cached)return JSON.parse(cached);}catch{}}return{};});
  const [history,setHistory]=useState<HistoryItem[]>([]);const [isLoading,setIsLoading]=useState(true);const [error]=useState<string|null>(null);
  useEffect(()=>{try{const settingsDocRef=doc(db,"settings","general");const unsubSettings=onSnapshot(settingsDocRef,(snapshot)=>{if(snapshot.exists()){const data=snapshot.data() as Partial<SettingsData>;const merged:SettingsData={...DEFAULT_SETTINGS,...data,deliveryLinks:{...DEFAULT_SETTINGS.deliveryLinks,...(data.deliveryLinks||{})},openingHours:{...DEFAULT_SETTINGS.openingHours,...(data.openingHours||{})},tickerMessages:data.tickerMessages?.length?data.tickerMessages:DEFAULT_SETTINGS.tickerMessages};setSettings(merged);try{localStorage.setItem("bk_settings",JSON.stringify(merged));}catch{}}setIsLoading(false);},(err)=>{console.warn("Firestore settings subscription fallback:",err.message);setIsLoading(false);});const overridesDocRef=doc(db,"menu_overrides","items");const unsubOverrides=onSnapshot(overridesDocRef,(snapshot)=>{if(snapshot.exists()){const data=snapshot.data() as{items?:Record<string,DishOverride>};if(data.items){setMenuOverrides(data.items);try{localStorage.setItem("bk_menu_overrides",JSON.stringify(data.items));}catch{}}}},(err)=>console.warn("Firestore menu overrides subscription fallback:",err.message));const unsubPromos=onSnapshot(collection(db,"promotions"),(snapshot)=>{const loadedPromos:Promotion[]=[];snapshot.forEach(d=>loadedPromos.push({id:d.id,...d.data()} as Promotion));setPromotions(loadedPromos);},(err)=>console.warn("Firestore promotions subscription fallback:",err.message));const historyQuery=query(collection(db,"history"),orderBy("timestamp","desc"),limit(50));const unsubHistory=onSnapshot(historyQuery,(snapshot)=>{const loadedHistory:HistoryItem[]=[];snapshot.forEach(d=>loadedHistory.push({id:d.id,...d.data()} as HistoryItem));setHistory(loadedHistory);},()=>{});return()=>{unsubSettings();unsubOverrides();unsubPromos();unsubHistory();};}catch(e:any){console.warn("Firebase initialization warning:",e?.message);setIsLoading(false);}},[]);
  const isPromotionActiveNow=(promo:Promotion):boolean=>{if(promo.status==="paused")return false;const now=Date.now();if(promo.startDate&&now<new Date(promo.startDate).getTime())return false;if(promo.endDate&&now>new Date(promo.endDate).getTime())return false;return promo.status==="active"||promo.status==="scheduled";};
  const activePromotions=useMemo(()=>promotions.filter(isPromotionActiveNow),[promotions]);
  const getDishPrice=(id:string,d:number|null)=>menuOverrides[id]?.price!==undefined?menuOverrides[id].price!:d;
  const getDishSizePrice=(id:string,sizeId:string,d:number|null)=>menuOverrides[id]?.sizePrices&&Object.prototype.hasOwnProperty.call(menuOverrides[id].sizePrices,sizeId)?menuOverrides[id].sizePrices![sizeId]??null:d;
  const isDishAvailable=(id:string)=>menuOverrides[id]?.isAvailable!==undefined?menuOverrides[id].isAvailable!:true;
  const isDishFeatured=(id:string,d:boolean)=>menuOverrides[id]?.isFeatured!==undefined?menuOverrides[id].isFeatured!:d;
  const getDishName=(id:string,d:Localized):Localized=>{const o=menuOverrides[id];return o?{pt:o.namePt||d.pt,en:o.nameEn||d.en}:d;};
  const getDishDescription=(id:string,d?:Localized):Localized|undefined=>{const o=menuOverrides[id];if(!o||(!o.descriptionPt&&!o.descriptionEn))return d;return{pt:o.descriptionPt!==undefined?o.descriptionPt:(d?.pt||""),en:o.descriptionEn!==undefined?o.descriptionEn:(d?.en||"")};};
  const getDishImage=(id:string,d?:string)=>menuOverrides[id]?.imageUrl||d;
  const recordHistory=async(action:string,details:string,userEmail="Owner")=>{try{await addDoc(collection(db,"history"),{timestamp:new Date().toISOString(),action,details,userEmail});}catch(e){console.warn("Could not save history:",e);}};
  const updateSettings=async(newSettings:Partial<SettingsData>,userEmail?:string)=>{const merged={...settings,...newSettings,updatedAt:new Date().toISOString()};setSettings(merged);await setDoc(doc(db,"settings","general"),merged,{merge:true});await recordHistory("Updated Settings","Updated restaurant settings/links",userEmail);};
  const updateDishOverride=async(dishId:string,override:Partial<DishOverride>,userEmail?:string,actionName?:string)=>{const updated={...menuOverrides,[dishId]:{...(menuOverrides[dishId]||{}),...override}};setMenuOverrides(updated);await setDoc(doc(db,"menu_overrides","items"),{items:updated,updatedAt:new Date().toISOString()},{merge:true});await recordHistory(actionName||`Updated Dish (${dishId})`,JSON.stringify(override),userEmail);};
  const toggleDishAvailability=async(dishId:string,isAvailable:boolean,dishName?:string,userEmail?:string)=>updateDishOverride(dishId,{isAvailable},userEmail,`${dishName||dishId} marked as ${isAvailable?"AVAILABLE":"SOLD OUT"}`);
  const savePromotion=async(promo:Omit<Promotion,"createdAt"|"updatedAt">|Promotion,userEmail?:string)=>{const now=new Date().toISOString();if("id" in promo&&promo.id){const{id,...data}=promo;await setDoc(doc(db,"promotions",id),{...data,updatedAt:now},{merge:true});await recordHistory("Updated Promotion",`Updated ${promo.title}`,userEmail);}else{await addDoc(collection(db,"promotions"),{...promo,createdAt:now,updatedAt:now});await recordHistory("Created Promotion",`Created ${promo.title}`,userEmail);}};
  const togglePromotionStatus=async(id:string,newStatus:"active"|"paused"|"scheduled",userEmail?:string)=>{await updateDoc(doc(db,"promotions",id),{status:newStatus,updatedAt:new Date().toISOString()});await recordHistory("Changed Promotion Status",`Status changed to ${newStatus}`,userEmail);};
  const deletePromotion=async(id:string,userEmail?:string)=>{await deleteDoc(doc(db,"promotions",id));await recordHistory("Deleted Promotion",`Deleted promotion ID ${id}`,userEmail);};
  return <RestaurantContext.Provider value={{settings,promotions,menuOverrides,history,isLoading,error,isPromotionActiveNow,activePromotions,getDishPrice,getDishSizePrice,isDishAvailable,isDishFeatured,getDishName,getDishDescription,getDishImage,updateSettings,updateDishOverride,toggleDishAvailability,savePromotion,togglePromotionStatus,deletePromotion,recordHistory}}>{children}</RestaurantContext.Provider>;
}
export function useRestaurantData(){const context=useContext(RestaurantContext);if(!context)throw new Error("useRestaurantData must be used within a RestaurantDataProvider");return context;}
