import { useEffect, useState } from "react";
import { useI18n } from "@/lib/i18n";
import { copy, fill, weekdayName, type HoursStatus } from "@/lib/restaurant";
import { getManagedHoursStatus, useRestaurantData, type WeekHours } from "@/lib/restaurant-context";
import { cn } from "@/lib/utils";
const WEEK_DAYS:Array<{key:keyof WeekHours;dayIndex:number}>=[{key:"monday",dayIndex:1},{key:"tuesday",dayIndex:2},{key:"wednesday",dayIndex:3},{key:"thursday",dayIndex:4},{key:"friday",dayIndex:5},{key:"saturday",dayIndex:6},{key:"sunday",dayIndex:0}];
function useHoursStatus(openingHours:WeekHours){const[status,setStatus]=useState<HoursStatus|null>(null);useEffect(()=>{const tick=()=>setStatus(getManagedHoursStatus(openingHours,new Date()));tick();const id=window.setInterval(tick,30000);const onVisible=()=>{if(document.visibilityState==="visible")tick();};document.addEventListener("visibilitychange",onVisible);return()=>{window.clearInterval(id);document.removeEventListener("visibilitychange",onVisible);};},[openingHours]);return status;}
function StatusLine({status}:{status:HoursStatus}){const{t}=useI18n();if(status.isOpen)return <p className="text-sm font-medium text-orange" aria-live="polite">{t(copy.openNow)}<span className="text-muted"> · {t(fill(copy.untilTime,{time:status.todayClose}))}</span></p>;const next=status.opensLaterToday?t(fill(copy.opensAt,{time:status.nextOpenTime})):t(fill(copy.opensDayAt,{day:t(weekdayName[status.nextOpenDay]),time:status.nextOpenTime}));return <p className="text-sm text-muted" aria-live="polite"><span className="font-medium text-cream/80">{t(copy.closedNow)}</span> · {next}</p>;}
export function HoursCompact({className}:{className?:string}){const{t}=useI18n();const{settings}=useRestaurantData();const status=useHoursStatus(settings.openingHours);if(!status)return null;return <div className={cn("text-sm leading-relaxed text-muted",className)}><p>{t(weekdayName[new Date().getDay()])}: {status.todayOpen}–{status.todayClose}</p><StatusLine status={status}/></div>;}
export function HoursBlock(){const{t,lang}=useI18n();const{settings}=useRestaurantData();const status=useHoursStatus(settings.openingHours);const isPt=lang==="pt";return <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-faint">{t(copy.hoursLabel)}</p><dl className="mt-3 max-w-sm space-y-1.5 text-cream">{WEEK_DAYS.map(({key,dayIndex})=>{const day=settings.openingHours[key];return <div key={key} className="flex items-baseline justify-between gap-6"><dt className="text-muted">{t(weekdayName[dayIndex])}</dt><dd className="tabular-nums tracking-wide">{day.isClosed?(isPt?"Fechado":"Closed"):`${day.open}–${day.close}`}</dd></div>;})}</dl>{status?<div className="mt-3"><StatusLine status={status}/></div>:null}</div>;}
